kind: Secret
apiVersion: v1
metadata:
  name: git-basic-auth
  namespace: tekton-tasks
type: Opaque
stringData:
  .gitconfig: |
    [credential "https://github.com"]
      helper = store
  .git-credentials: |
    https://danieltmc:3958mccloskey@github.com
