apiVersion: v1
kind: PersistentVolume
metadata:
  name: api-source-volume
  namespace: tekton-tasks
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /path/on/host
