apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ci-cd-api-argo-31
  namespace: tekton-tasks
spec:
  pipelineRef:
    name: build-and-deploy-pipeline-argo
  podTemplate:
    securityContext:
      fsGroup: 65532
  params:
    - name: gitUrl
      value: https://github.com/Acuity-Inc/tech-challenge-ci-cd-api.git
    - name: gitRevision
      value: master
    - name: imageUrl
      value: danieltmcc/tsg-innolab-cicd-api
    - name: imageTag
      value: '1.0'
    - name: pathToYamlFile
      value: manifest.yaml
    - name: manifestUrl
      value: https://github.com/Acuity-Inc/tsg-innolab-cncf-delivery-bakeoff
  serviceAccountName: tekton-sa
  workspaces:
    - name: git-source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce # access mode may affect how you can use this volume in parallel tasks
          resources:
            requests:
              storage: 1Gi
    - name: manifest-source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: git-ssh
      secret:
        secretName: git-ssh
