apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"tekton-sa","namespace":"tekton-tasks"},"secrets":[{"name":"tekton-git-creds"}]}
  creationTimestamp: "2023-10-03T22:42:38Z"
  name: tekton-sa
  namespace: tekton-tasks
  resourceVersion: "17930727"
  uid: f1302511-41b0-465e-a899-26f2ee61e2a6
secrets:
- name: tekton-git-creds
- name: regcred