apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-source-pvc
  namespace: tekton-tasks
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: api-source-pvc
  accessModes:
    -  ReadWriteOnce
  resources:
    requests:
      storage: 1Gi